language: cpp

dist: bionic

jobs:
  include:
    - os: osx
      osx_image: xcode10    # OS X 10.13 (oldest Xcode/macOS we support)
    - os: osx
      osx_image: xcode12    # OS X 10.15.5
    - os: linux             # see dist above
      compiler: clang
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - echo Lang:$LANG. OS:$TRAVIS_OS_NAME. CC:$CC.
  - uname -a
  - |
    # if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    #   brew update
    #   if [ -z `brew list | grep cmake` ]; then brew install cmake; fi
    #   brew outdated cmake || brew upgrade cmake
    #   if [ -z `which ninja` ]; then brew install ninja; fi
    # fi
  - |
    # if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    #   sudo apt-get -qq update
    #   sudo apt-get install -y libc++-dev cmake ninja
    # fi

script:
  - ./ci/build.sh

notifications:
  email: false


